### ISSUE TITLE
Add direction to trains.json

### ISSUE THREAD

**Issue by russss** [stblassitude/c3toctrack#2]
It would be good to have a direction/course field (in degrees) in trains.json because it looks weird if a train icon is facing the wrong way on the map :)

**Comment by stblassitude** [comment]
I'll try and add that over the weekend.

**Comment by russss** [comment]
Thanks! Trains will appear on https://map.events.ccc.de once they are running (I'm filtering out the demo train on the live map).
<img width="1012" alt="image" src="https://github.com/stblassitude/c3toctrack/assets/45057/89687dd3-7298-4e07-931e-bfffeba8a19f">
